-- ============================================================================
-- Fin-Game — Initial Content Seeds
-- Run AFTER schema.sql. Safe to re-run (uses ON CONFLICT).
-- ============================================================================

-- -----------------------------------------------------------------------------
-- Courses
-- -----------------------------------------------------------------------------
insert into public.courses (
  id, title, title_ar, description, description_ar, topic, icon, color, sort_order, coin_reward
) values
  (
    'investing-basics',
    'Investing Basics',
    'أساسيات الاستثمار',
    'Learn fundamental investment principles',
    'تعلم مبادئ الاستثمار الأساسية',
    'investing',
    '📈',
    '#2563eb',
    1,
    200
  ),
  (
    'budgeting-101',
    'Budgeting 101',
    'الميزانية 101',
    'Master personal finance management',
    'إدارة المال الشخصي بذكاء',
    'budgeting',
    '💰',
    '#eab308',
    2,
    150
  ),
  (
    'stock-market',
    'Stock Market Essentials',
    'أساسيات سوق الأسهم',
    'Understand EGX dynamics and trading',
    'افهم ديناميكيات البورصة المصرية والتداول',
    'investing',
    '🏛️',
    '#a855f7',
    3,
    250
  ),
  (
    'credit-health',
    'Credit & Loans',
    'الائتمان والقروض',
    'Build a strong credit score in Egypt',
    'ابني تقييم ائتماني قوي في مصر',
    'saving',
    '💳',
    '#22c55e',
    4,
    200
  ),
  (
    'gold-silver',
    'Gold & Silver 101',
    'الذهب والفضة 101',
    'How precious metals protect wealth',
    'إزاي المعادن النفيسة تحمي ثروتك',
    'investing',
    '🥇',
    '#f97316',
    5,
    150
  )
on conflict (id) do update set
  title = excluded.title,
  title_ar = excluded.title_ar,
  description = excluded.description,
  description_ar = excluded.description_ar,
  topic = excluded.topic,
  icon = excluded.icon,
  color = excluded.color,
  sort_order = excluded.sort_order,
  coin_reward = excluded.coin_reward;

-- -----------------------------------------------------------------------------
-- Lessons
-- -----------------------------------------------------------------------------
insert into public.lessons (
  id, course_id, title, title_ar, summary, summary_ar, duration_minutes, sort_order
) values
  (
    'ib-1',
    'investing-basics',
    'Why Invest?',
    'ليه نستثمر؟',
    'Inflation and the cost of doing nothing.',
    'التضخم وتكلفة إنك ما تعملش حاجة.',
    6,
    1
  ),
  (
    'ib-2',
    'investing-basics',
    'Risk vs Return',
    'المخاطرة مقابل العائد',
    'Understand the trade-off.',
    'افهم المقايضة بين المخاطرة والعائد.',
    8,
    2
  ),
  (
    'ib-3',
    'investing-basics',
    'Diversification',
    'التنويع',
    'Don''t put all eggs in one basket.',
    'ما تحطش كل البيض في سلة واحدة.',
    7,
    3
  ),
  (
    'ib-4',
    'investing-basics',
    'Building a Portfolio',
    'بناء محفظة',
    'Allocating across assets.',
    'توزيع الاستثمار بين أصول مختلفة.',
    10,
    4
  ),

  (
    'bd-1',
    'budgeting-101',
    'The 50/30/20 Rule',
    'قاعدة 50/30/20',
    'Needs, wants, savings.',
    'احتياجات، رغبات، ادخار.',
    6,
    1
  ),
  (
    'bd-2',
    'budgeting-101',
    'Tracking Expenses',
    'تتبع المصاريف',
    'Knowing where your money goes.',
    'اعرف فلوسك رايحة فين.',
    5,
    2
  ),
  (
    'bd-3',
    'budgeting-101',
    'Emergency Fund',
    'صندوق الطوارئ',
    '3-6 months of expenses.',
    'من 3 لـ 6 شهور مصاريف.',
    7,
    3
  ),

  (
    'sm-1',
    'stock-market',
    'How EGX Works',
    'البورصة المصرية شغالة إزاي؟',
    'Indices: EGX30, EGX70.',
    'المؤشرات: EGX30 و EGX70.',
    8,
    1
  ),
  (
    'sm-2',
    'stock-market',
    'Reading a Stock Chart',
    'قراءة شارت السهم',
    'Candles, volumes, trendlines.',
    'شموع، حجم تداول، خطوط ترند.',
    10,
    2
  ),
  (
    'sm-3',
    'stock-market',
    'Order Types',
    'أنواع الأوامر',
    'Market, Limit, Stop-Loss.',
    'سوق، حد، وقف خسارة.',
    9,
    3
  ),

  (
    'cr-1',
    'credit-health',
    'What is a Credit Score?',
    'التصنيف الائتماني إيه؟',
    '300-850 and what affects it.',
    'من 300 لـ 850 وإيه اللي يأثر عليه.',
    7,
    1
  ),
  (
    'cr-2',
    'credit-health',
    'Credit Utilization',
    'استخدام الائتمان',
    'Why < 30% is key.',
    'ليه أقل من 30% مهم.',
    6,
    2
  ),
  (
    'cr-3',
    'credit-health',
    'Loan Amortization',
    'جدولة القرض',
    'How interest compounds monthly.',
    'إزاي الفايدة بتتراكب شهريًا.',
    8,
    3
  ),

  (
    'gs-1',
    'gold-silver',
    'Gold Karats 101',
    'عيارات الذهب 101',
    '24K vs 21K vs 18K.',
    '24 عيار مقابل 21 مقابل 18.',
    5,
    1
  ),
  (
    'gs-2',
    'gold-silver',
    'When to Buy Gold',
    'إمتى تشتري ذهب؟',
    'Inflation hedging basics.',
    'أساسيات التحوط ضد التضخم.',
    7,
    2
  )
on conflict (id) do update set
  course_id = excluded.course_id,
  title = excluded.title,
  title_ar = excluded.title_ar,
  summary = excluded.summary,
  summary_ar = excluded.summary_ar,
  duration_minutes = excluded.duration_minutes,
  sort_order = excluded.sort_order;

-- -----------------------------------------------------------------------------
-- Videos (small fast test MP4s — replace with your own hosted content later)
-- Using short MP4s from mixkit.co / w3schools which are small (<2MB) and load
-- quickly on slow networks. These are just placeholders so the player works.
-- -----------------------------------------------------------------------------
insert into public.videos (
  id, lesson_id, title, title_ar, url, thumbnail, duration_seconds, sort_order
) values
  (
    'v-ib-1',
    'ib-1',
    'Why Invest? — Intro',
    'ليه نستثمر؟ — مقدمة',
    'https://www.w3schools.com/html/mov_bbb.mp4',
    null,
    10,
    1
  ),
  (
    'v-ib-2',
    'ib-2',
    'Risk vs Return',
    'المخاطرة مقابل العائد',
    'https://www.w3schools.com/html/movie.mp4',
    null,
    6,
    1
  ),
  (
    'v-bd-1',
    'bd-1',
    'The 50/30/20 Rule',
    'قاعدة 50/30/20',
    'https://www.w3schools.com/html/mov_bbb.mp4',
    null,
    10,
    1
  ),
  (
    'v-sm-1',
    'sm-1',
    'How EGX Works',
    'البورصة المصرية شغالة إزاي؟',
    'https://www.w3schools.com/html/movie.mp4',
    null,
    6,
    1
  ),
  (
    'v-cr-1',
    'cr-1',
    'What is a Credit Score?',
    'التصنيف الائتماني إيه؟',
    'https://www.w3schools.com/html/mov_bbb.mp4',
    null,
    10,
    1
  ),
  (
    'v-gs-1',
    'gs-1',
    'Gold Karats 101',
    'عيارات الذهب 101',
    'https://www.w3schools.com/html/movie.mp4',
    null,
    6,
    1
  )
on conflict (id) do update set
  lesson_id = excluded.lesson_id,
  title = excluded.title,
  title_ar = excluded.title_ar,
  url = excluded.url,
  thumbnail = excluded.thumbnail,
  duration_seconds = excluded.duration_seconds,
  sort_order = excluded.sort_order;

-- -----------------------------------------------------------------------------
-- Marketplace products (credit cards)
-- -----------------------------------------------------------------------------
insert into public.marketplace_products (
  id, category, bank, logo, name, apr, annual_fee, cashback,
  rating, reviews_count, tier, min_income, min_age, min_credit_score,
  benefits, pros, cons, best_for, is_best_value, sort_order
) values
  (
    'cib-smart', 'credit-cards', 'CIB', '🏦', 'CIB Smart Credit Card',
    30, 300, 2,
    4.5, 124, 'strong', 5000, 21, 650,
    '["Airport lounge","Cashback","Travel insurance"]'::jsonb,
    '["2% cashback on all purchases","Airport lounge access","Travel insurance included","No foreign transaction fees"]'::jsonb,
    '["Annual fee of EGP 300","APR higher than market average"]'::jsonb,
    'Regular spenders with travel needs',
    true,
    1
  ),
  (
    'nbe-platinum', 'credit-cards', 'NBE', '🏛️', 'NBE Platinum Card',
    35, 500, 1.5,
    4.2, 87, 'moderate', 8000, 25, 700,
    '["Reward points","Purchase protection"]'::jsonb,
    '["Premium rewards program","Purchase protection up to EGP 50k"]'::jsonb,
    '["High annual fee","High APR","High income requirement"]'::jsonb,
    'High earners seeking premium perks',
    false,
    2
  ),
  (
    'misr-gold', 'credit-cards', 'Banque Misr', '🏢', 'Misr Gold Card',
    32, 250, 1,
    4.0, 56, 'strong', 4000, 21, 620,
    '["Free ATM withdrawals","Balance transfer"]'::jsonb,
    '["Free ATM at any bank","Low annual fee","Balance transfer option"]'::jsonb,
    '["Limited rewards","No travel perks"]'::jsonb,
    'Everyday banking essentials',
    false,
    3
  ),
  (
    'hsbc-premier', 'credit-cards', 'HSBC', '🏪', 'HSBC Premier Card',
    42, 800, 3,
    4.8, 203, 'high', 15000, 28, 750,
    '["Concierge service","Priority banking","Global coverage"]'::jsonb,
    '["3% cashback on all spend","24/7 concierge service","Global lounge access","Priority banking queue"]'::jsonb,
    '["Very high annual fee","Highest APR on market","Strict eligibility"]'::jsonb,
    'Executives with global lifestyle',
    false,
    4
  ),
  (
    'alex-student', 'credit-cards', 'Alex Bank', '🏬', 'Alex Student Card',
    28, 0, 0.5,
    3.8, 41, 'strong', 0, 18, 0,
    '["No annual fee","Student discounts"]'::jsonb,
    '["Zero annual fee","No minimum income","Student discount partners","Lowest APR"]'::jsonb,
    '["Very low cashback","No premium perks"]'::jsonb,
    'Students & first-time users',
    false,
    5
  )
on conflict (id) do update set
  category = excluded.category,
  bank = excluded.bank,
  logo = excluded.logo,
  name = excluded.name,
  apr = excluded.apr,
  annual_fee = excluded.annual_fee,
  cashback = excluded.cashback,
  rating = excluded.rating,
  reviews_count = excluded.reviews_count,
  tier = excluded.tier,
  min_income = excluded.min_income,
  min_age = excluded.min_age,
  min_credit_score = excluded.min_credit_score,
  benefits = excluded.benefits,
  pros = excluded.pros,
  cons = excluded.cons,
  best_for = excluded.best_for,
  is_best_value = excluded.is_best_value,
  sort_order = excluded.sort_order;

-- -----------------------------------------------------------------------------
-- Quizzes
-- -----------------------------------------------------------------------------
insert into public.quizzes (
  id, title, title_ar, description, description_ar, category, difficulty, coin_reward
) values
  (
    'quiz-investing',
    'Investing Fundamentals',
    'أساسيات الاستثمار',
    'Test your investment knowledge',
    'اختبر معلوماتك في الاستثمار',
    'investing',
    'easy',
    50
  ),
  (
    'quiz-budgeting',
    'Smart Budgeting',
    'ميزانية ذكية',
    'Master money management',
    'إدارة فلوسك بشكل عملي',
    'budgeting',
    'easy',
    40
  ),
  (
    'quiz-egx',
    'EGX & Stocks',
    'EGX والأسهم',
    'Egyptian Exchange quiz',
    'كويز عن البورصة المصرية',
    'stocks',
    'medium',
    75
  ),
  (
    'quiz-credit',
    'Credit & Loans',
    'الائتمان والقروض',
    'Understand credit scoring',
    'افهم التصنيف الائتماني',
    'credit',
    'medium',
    75
  ),
  (
    'quiz-gold',
    'Gold & Silver',
    'الذهب والفضة',
    'Precious metals basics',
    'أساسيات المعادن النفيسة',
    'gold',
    'easy',
    40
  )
on conflict (id) do update set
  title = excluded.title,
  title_ar = excluded.title_ar,
  description = excluded.description,
  description_ar = excluded.description_ar,
  category = excluded.category,
  difficulty = excluded.difficulty,
  coin_reward = excluded.coin_reward;

-- -----------------------------------------------------------------------------
-- Questions (50+)
-- -----------------------------------------------------------------------------
insert into public.questions (
  id,
  quiz_id,
  question,
  question_ar,
  options,
  options_ar,
  correct_index,
  explanation,
  explanation_ar,
  sort_order
) values
  -- Investing (10 Q)
  ('q-inv-01', 'quiz-investing', 'What does diversification mean?',
   'إيه معنى التنويع؟',
   '["Putting all money in one stock","Spreading investments across assets","Buying only bonds","Day trading"]'::jsonb,
   '["تحط كل فلوسك في سهم واحد","توزع استثماراتك على أصول مختلفة","تشتري سندات بس","تداول يومي"]'::jsonb,
   1,
   'Diversification reduces risk by spreading investments across different assets.',
   'التنويع بيقلل المخاطرة لما توزع استثماراتك على أصول مختلفة.',
   1),
  ('q-inv-02', 'quiz-investing', 'Higher potential return generally means...',
   'العائد الأعلى المتوقع غالبًا يعني...',
   '["Lower risk","Same risk","Higher risk","No risk"]'::jsonb,
   '["مخاطرة أقل","نفس المخاطرة","مخاطرة أعلى","مافيش مخاطرة"]'::jsonb,
   2,
   'Risk and return are positively correlated in most investments.',
   'في أغلب الاستثمارات، المخاطرة والعائد بيرتبطوا إيجابيًا.',
   2),
  ('q-inv-03', 'quiz-investing', 'What is inflation?',
   'إيه هو التضخم؟',
   '["Stock price going up","Fall in money purchasing power","Currency exchange rate","Interest rate"]'::jsonb,
   '["سعر السهم بيطلع","انخفاض قدرة الفلوس على الشراء","سعر صرف العملة","معدل الفايدة"]'::jsonb,
   1,
   'Inflation erodes the purchasing power of money over time.',
   'التضخم بيقلل قدرة الفلوس على الشراء مع الوقت.',
   3),
  ('q-inv-04', 'quiz-investing', 'A "bear market" refers to...',
   'سوق الدببة (Bear market) يقصد بيه...',
   '["Rising prices","Falling prices","Stable prices","IPO season"]'::jsonb,
   '["أسعار طالعة","أسعار نازلة","أسعار ثابتة","موسم الطروحات"]'::jsonb,
   1,
   'Bear market = prolonged decline of 20% or more.',
   'سوق هابط غالبًا يعني هبوط مستمر حوالي 20% أو أكتر.',
   4),
  ('q-inv-05', 'quiz-investing', 'Compound interest is...',
   'الفايدة المركبة يعني...',
   '["Interest on principal only","Interest on principal + accumulated interest","A type of bond","A tax"]'::jsonb,
   '["فايدة على الأصل بس","فايدة على الأصل + الفوايد المتراكمة","نوع سند","ضريبة"]'::jsonb,
   1,
   'Compound interest grows exponentially because you earn interest on previous interest.',
   'الفايدة المركبة بتكبر لأنك بتكسب فايدة على الفايدة المتراكمة كمان.',
   5),
  ('q-inv-06', 'quiz-investing', 'What is a mutual fund?',
   'إيه هو صندوق الاستثمار المشترك؟',
   '["A single stock","A pool of investor money in multiple securities","A bank account","A loan"]'::jsonb,
   '["سهم واحد","تجميع فلوس مستثمرين في أوراق مالية متعددة","حساب بنكي","قرض"]'::jsonb,
   1,
   'Mutual funds pool money from many investors to buy a diversified portfolio.',
   'الصندوق بيجمع فلوس ناس كتير عشان يشتري محفظة متنوعة.',
   6),
  ('q-inv-07', 'quiz-investing', 'Which typically has LOWER risk?',
   'أيه غالبًا أقل مخاطرة؟',
   '["Individual stocks","Government bonds","Cryptocurrency","Options"]'::jsonb,
   '["أسهم فردية","سندات حكومية","كريبتو","أوبشن"]'::jsonb,
   1,
   'Government bonds are historically among the safest investments.',
   'سندات الحكومة تاريخيًا من الأقل مخاطرة مقارنة بأصول تانية.',
   7),
  ('q-inv-08', 'quiz-investing', 'Dollar-cost averaging means...',
   'متوسط تكلفة الدولار (DCA) يعني...',
   '["Buying at the bottom","Investing fixed amount regularly","Selling high","Timing the market"]'::jsonb,
   '["الشراء عند القاع","استثمار مبلغ ثابت بشكل منتظم","بيع عالي","توقيت السوق"]'::jsonb,
   1,
   'DCA smooths out volatility by investing on a schedule regardless of price.',
   'DCA يعني تستثمر مبلغ ثابت بشكل منتظم عشان تهدي تقلبات السعر.',
   8),
  ('q-inv-09', 'quiz-investing', 'What is an ETF?',
   'إيه هو ETF؟',
   '["Exchange Traded Fund","Emergency Tax Fee","Equity Trust Fund","Exchange Trust Foundation"]'::jsonb,
   '["صندوق متداول في البورصة","رسوم طوارئ ضريبية","صندوق أمانة أسهم","مؤسسة أمانة تداول"]'::jsonb,
   0,
   'ETFs trade like stocks but hold baskets of assets.',
   'ETF بيتداول زي السهم لكنه بيمسك سلة من الأصول.',
   9),
  ('q-inv-10', 'quiz-investing', 'Time in the market beats...',
   'الوقت داخل السوق بيكسب...',
   '["Luck","Timing the market","Hard work","Research"]'::jsonb,
   '["الحظ","توقيت السوق","شغل جامد","بحث"]'::jsonb,
   1,
   'Long-term consistency usually outperforms trying to time tops and bottoms.',
   'الاستمرار على المدى الطويل غالبًا أحسن من محاولة توقيت القمم والقيعان.',
   10),

  -- Budgeting (10 Q)
  ('q-bud-01', 'quiz-budgeting', 'The 50/30/20 rule allocates income to...',
   'قاعدة 50/30/20 بتقسم الدخل على...',
   '["50% needs, 30% wants, 20% savings","All savings","Taxes only","Random"]'::jsonb,
   '["50% احتياجات، 30% رغبات، 20% ادخار","كلها ادخار","ضرائب بس","عشوائي"]'::jsonb,
   0,
   '50/30/20: needs / wants / savings & debt payoff.',
   '50/30/20: احتياجات / رغبات / ادخار وسداد ديون.',
   1),
  ('q-bud-02', 'quiz-budgeting', 'How many months of expenses should your emergency fund cover?',
   'صندوق الطوارئ المفروض يغطي كام شهر مصاريف؟',
   '["1","2","3-6","12+"]'::jsonb,
   '["1 شهر","2 شهر","3-6 شهور","12+ شهر"]'::jsonb,
   2,
   'Most advisors recommend 3 to 6 months of expenses.',
   'أغلب التوصيات: من 3 لـ 6 شهور مصاريف.',
   2),
  ('q-bud-03', 'quiz-budgeting', 'A "need" is best described as...',
   'الاحتياج (Need) يوصف بأحسن شكل إنه...',
   '["Latest phone","Food and shelter","Concert ticket","Luxury car"]'::jsonb,
   '["أحدث موبايل","أكل وسكن","تذكرة حفلة","عربية فارهة"]'::jsonb,
   1,
   'Needs = essentials for survival (food, shelter, medicine).',
   'الاحتياجات = أساسيات العيش (أكل، سكن، دواء...).',
   3),
  ('q-bud-04', 'quiz-budgeting', 'Tracking expenses helps you...',
   'تتبع المصاريف بيساعدك إنك...',
   '["Spend more","See where money goes","Avoid taxes","Increase salary"]'::jsonb,
   '["تصرف أكتر","تشوف الفلوس رايحة فين","تهرب من الضرائب","تزود المرتب"]'::jsonb,
   1,
   'Awareness is the first step to controlling spending.',
   'الوعي أول خطوة للسيطرة على الإنفاق.',
   4),
  ('q-bud-05', 'quiz-budgeting', 'Which is a fixed expense?',
   'أيه من دول مصروف ثابت؟',
   '["Groceries","Rent","Entertainment","Eating out"]'::jsonb,
   '["بقالة","إيجار","ترفيه","أكل برا"]'::jsonb,
   1,
   'Rent is fixed each month; groceries and entertainment vary.',
   'الإيجار ثابت شهريًا؛ البقالة والترفيه بتتغير.',
   5),
  ('q-bud-06', 'quiz-budgeting', 'Zero-based budgeting means...',
   'ميزانية الصفر (Zero-based) يعني...',
   '["Spend nothing","Every pound has a job","Budget = 0","Save 0%"]'::jsonb,
   '["متصرفش خالص","كل جنيه له وظيفة","الميزانية = صفر","ادخر 0%"]'::jsonb,
   1,
   'Every unit of income is assigned a purpose until income - expenses = 0.',
   'كل جنيه من الدخل له وظيفة لحد ما الدخل - المصاريف = 0.',
   6),
  ('q-bud-07', 'quiz-budgeting', 'What is the main risk of living paycheck to paycheck?',
   'أخطر حاجة في العيش من مرتب لمرتب إيه؟',
   '["Too much savings","No buffer for emergencies","High credit score","Lower taxes"]'::jsonb,
   '["ادخار زيادة","مفيش وسادة للطوارئ","تصنيف ائتماني عالي","ضرائب أقل"]'::jsonb,
   1,
   'One unexpected expense can cascade into debt.',
   'مصروف طارئ واحد ممكن يبدأ سلسلة ديون.',
   7),
  ('q-bud-08', 'quiz-budgeting', 'Pay yourself first means...',
   'ادفع لنفسك الأول يعني...',
   '["Save before spending","Buy luxuries first","Skip bills","Work overtime"]'::jsonb,
   '["تدخر قبل ما تصرف","تشتري الرفاهية الأول","تتجنب الفواتير","ساعات إضافية"]'::jsonb,
   0,
   'Automate savings before you have a chance to spend.',
   'خلي الادخار أوتوماتيك قبل ما تفوتك فرصة الصرف.',
   8),
  ('q-bud-09', 'quiz-budgeting', 'Which tool tracks net worth over time?',
   'أيه أداة بتتابع صافي الثروة مع الوقت؟',
   '["Calculator","Budget app / spreadsheet","Social media","News"]'::jsonb,
   '["آلة حاسبة","تطبيق ميزانية / جدول","سوشيال ميديا","أخبار"]'::jsonb,
   1,
   'A budgeting tool or spreadsheet logs assets - liabilities.',
   'جدول/تطبيق ميزانية بيسجل الأصول ناقص الالتزامات.',
   9),
  ('q-bud-10', 'quiz-budgeting', 'Cutting which expense usually helps most?',
   'تقليل أنهي مصروف غالبًا بيفرق أكتر؟',
   '["Coffee","Rent/housing","Netflix","Gum"]'::jsonb,
   '["قهوة","إيجار/سكن","نتفليكس","علكة"]'::jsonb,
   1,
   'Housing is typically the largest line item in a budget.',
   'السكن غالبًا أكبر بند في الميزانية.',
   10),

  -- EGX / Stocks (10 Q)
  ('q-egx-01', 'quiz-egx', 'EGX30 tracks...',
   'EGX30 بيقيس...',
   '["30 largest companies on the Egyptian Exchange","Global stocks","EGX bonds","Only banks"]'::jsonb,
   '["أكبر 30 شركة في البورصة المصرية","أسهم عالمية","سندات البورصة المصرية","بنوك فقط"]'::jsonb,
   0,
   'EGX30 is the flagship index of the top 30 EG-listed companies.',
   'EGX30 مؤشر لأكبر 30 شركة في البورصة المصرية.',
   1),
  ('q-egx-02', 'quiz-egx', 'COMI on the EGX stands for...',
   'COMI على EGX بتقصد...',
   '["Commercial International Bank","Coca-Mit","Cairo Motors","COMESA Industries"]'::jsonb,
   '["البنك التجاري الدولي","كوكا-ميت","قاهرة موتورز","كوميسا للصناعات"]'::jsonb,
   0,
   'COMI = Commercial International Bank, Egypt''s largest private bank.',
   'COMI = البنك التجاري الدولي (CIB).',
   2),
  ('q-egx-03', 'quiz-egx', 'A "Limit Order" guarantees...',
   'أمر الحد (Limit) بيضمن...',
   '["Execution at any price","Execution at your price or better","Lowest price","Same-day execution"]'::jsonb,
   '["تنفيذ بأي سعر","تنفيذ بسعرك أو أحسن","أقل سعر","تنفيذ في نفس اليوم"]'::jsonb,
   1,
   'Limit orders only fill at your specified price (or better), not worse.',
   'أمر الحد ينفذ بسعرك أو أحسن… مش أسوأ.',
   3),
  ('q-egx-04', 'quiz-egx', 'Stop-Loss is used to...',
   'وقف الخسارة (Stop-Loss) بيستخدم عشان...',
   '["Lock in gains","Limit losses","Double positions","Skip taxes"]'::jsonb,
   '["تثبيت الأرباح","تحديد الخسائر","مضاعفة المراكز","تتجنب الضرائب"]'::jsonb,
   1,
   'A stop-loss auto-sells if the price drops to a trigger level.',
   'وقف الخسارة بيبيع تلقائيًا لو السعر وصل لمستوى محدد.',
   4),
  ('q-egx-05', 'quiz-egx', 'Market order executes...',
   'أمر السوق (Market) بينفذ...',
   '["At your specified price","At the best available price immediately","Tomorrow","After hours"]'::jsonb,
   '["بسعرك المحدد","بأحسن سعر متاح فورًا","بكره","بعد إغلاق الجلسة"]'::jsonb,
   1,
   'Market orders fill now at whatever price is available.',
   'أمر السوق بينفذ فورًا بأحسن سعر متاح دلوقتي.',
   5),
  ('q-egx-06', 'quiz-egx', 'P/E ratio measures...',
   'نسبة P/E بتقيس...',
   '["Price-to-earnings","Profit-to-equity","Price-to-employees","Profit-to-expenses"]'::jsonb,
   '["السعر إلى الأرباح","الربح إلى حقوق الملكية","السعر إلى الموظفين","الربح إلى المصاريف"]'::jsonb,
   0,
   'P/E = Price per share / Earnings per share.',
   'P/E = سعر السهم ÷ ربحية السهم.',
   6),
  ('q-egx-07', 'quiz-egx', 'Dividend is...',
   'التوزيعات (Dividend) يعني...',
   '["Stock split","Share of profit paid to shareholders","Company debt","Tax"]'::jsonb,
   '["تجزئة سهم","حصة أرباح تدفع للمساهمين","دين الشركة","ضريبة"]'::jsonb,
   1,
   'Dividends are cash (or stock) payments distributed to shareholders.',
   'توزيعات = جزء من الأرباح يتدفع للمساهمين.',
   7),
  ('q-egx-08', 'quiz-egx', 'Bull market means...',
   'سوق الثيران (Bull) يعني...',
   '["Falling prices","Rising prices","Flat prices","No trading"]'::jsonb,
   '["أسعار نازلة","أسعار طالعة","أسعار ثابتة","مافيش تداول"]'::jsonb,
   1,
   'Bull = rising, Bear = falling.',
   'ثور = صاعد… دب = هابط.',
   8),
  ('q-egx-09', 'quiz-egx', 'Volume indicates...',
   'حجم التداول (Volume) بيعبر عن...',
   '["Price","Number of shares traded","P/E","Dividend"]'::jsonb,
   '["السعر","عدد الأسهم المتداولة","P/E","توزيعات"]'::jsonb,
   1,
   'Volume = how many shares changed hands in a period.',
   'الحجم = عدد الأسهم المتداولة في فترة.',
   9),
  ('q-egx-10', 'quiz-egx', 'What is an IPO?',
   'إيه هو الـ IPO؟',
   '["Initial Public Offering","International Payment Option","Index Performance Order","None"]'::jsonb,
   '["طرح أولي عام","خيار دفع دولي","أمر أداء المؤشر","ولا واحد"]'::jsonb,
   0,
   'IPO = when a company first sells shares to the public.',
   'IPO = أول مرة الشركة تعرض أسهمها للجمهور.',
   10),

  -- Credit (10 Q)
  ('q-crd-01', 'quiz-credit', 'Credit score ranges typically from...',
   'نطاق الـ credit score غالبًا من...',
   '["0-100","300-850","500-1000","1-10"]'::jsonb,
   '["0-100","300-850","500-1000","1-10"]'::jsonb,
   1,
   'FICO score ranges from 300 (poor) to 850 (excellent).',
   'نطاق FICO من 300 (ضعيف) لـ 850 (ممتاز).',
   1),
  ('q-crd-02', 'quiz-credit', 'Credit utilization should stay BELOW...',
   'استخدام الائتمان المفروض يفضل أقل من...',
   '["10%","30%","70%","100%"]'::jsonb,
   '["10%","30%","70%","100%"]'::jsonb,
   1,
   'Keeping utilization below 30% helps your credit score.',
   'إنك تفضل تحت 30% بيساعد التصنيف الائتماني.',
   2),
  ('q-crd-03', 'quiz-credit', 'Which hurts your score MOST?',
   'أيه بيضر التصنيف أكتر؟',
   '["Paying on time","Missed payment","Low utilization","Long history"]'::jsonb,
   '["السداد في الموعد","تأخر أو عدم سداد","استخدام منخفض","تاريخ طويل"]'::jsonb,
   1,
   'Payment history is the biggest factor (~35% of FICO).',
   'تاريخ السداد أكبر عامل (حوالي 35% من FICO).',
   3),
  ('q-crd-04', 'quiz-credit', 'APR stands for...',
   'APR يعني...',
   '["Annual Percentage Rate","Average Payment Ratio","Auto Price Rate","Annual Premium Rate"]'::jsonb,
   '["معدل النسبة السنوية","متوسط نسبة الدفع","سعر تلقائي","قسط سنوي"]'::jsonb,
   0,
   'APR = yearly cost of borrowing as a percentage.',
   'APR = تكلفة الاقتراض السنوية كنسبة مئوية.',
   4),
  ('q-crd-05', 'quiz-credit', 'Closing a credit card can...',
   'إغلاق كارت ائتمان ممكن...',
   '["Raise your score","Lower your score","Do nothing","Double your limit"]'::jsonb,
   '["يرفع التصنيف","يقلل التصنيف","مافيش تأثير","يضاعف الحد"]'::jsonb,
   1,
   'Closing a card reduces total credit limit, raising utilization ratio.',
   'إغلاق الكارت يقلل الحد الإجمالي ويرفع نسبة الاستخدام.',
   5),
  ('q-crd-06', 'quiz-credit', 'Minimum payment on credit card means...',
   'الحد الأدنى للسداد على الكارت يعني...',
   '["Pay full balance","Pay smallest amount to avoid penalty","Pay APR only","Skip payment"]'::jsonb,
   '["تسدد الرصيد كامل","تدفع أقل مبلغ لتجنب غرامة","تدفع الفايدة فقط","تتخطى السداد"]'::jsonb,
   1,
   'Paying only minimum keeps you in debt longer due to interest.',
   'سداد الحد الأدنى بيطول المديونية بسبب الفوائد.',
   6),
  ('q-crd-07', 'quiz-credit', 'Loan amortization is...',
   'جدولة سداد القرض (Amortization) يعني...',
   '["Interest-only payment","Gradual payment of principal + interest","One-time payoff","Late fee"]'::jsonb,
   '["دفع فوايد فقط","سداد تدريجي للأصل + الفوايد","سداد مرة واحدة","رسوم تأخير"]'::jsonb,
   1,
   'Amortization spreads principal and interest across scheduled payments.',
   'الجدولة بتوزع الأصل والفايدة على دفعات منتظمة.',
   7),
  ('q-crd-08', 'quiz-credit', 'A "secured" loan requires...',
   'القرض المضمون (secured) محتاج...',
   '["Nothing","Collateral","Guarantor","Insurance"]'::jsonb,
   '["ولا حاجة","رهن أو ضمان","كفيل","تأمين"]'::jsonb,
   1,
   'Secured loans are backed by collateral (e.g., car, home).',
   'القرض المضمون مربوط برهن/ضمان (زي عربية أو عقار).',
   8),
  ('q-crd-09', 'quiz-credit', 'Best way to build credit from scratch?',
   'أحسن طريقة تبني ائتمان من الصفر؟',
   '["Avoid credit entirely","Use a starter card responsibly","Borrow maximum","Miss payments"]'::jsonb,
   '["تتجنب الائتمان خالص","تستخدم كارت بداية بمسؤولية","اقترض أقصى حد","تفوت مواعيد السداد"]'::jsonb,
   1,
   'A small starter card with on-time payments builds history.',
   'كارت بداية صغير + سداد في الموعد يبني تاريخ.',
   9),
  ('q-crd-10', 'quiz-credit', 'Debt-to-income (DTI) ratio measures...',
   'نسبة الديون للدخل (DTI) بتقيس...',
   '["Assets/Liabilities","Monthly debt / Monthly income","Taxes","Savings"]'::jsonb,
   '["أصول/التزامات","ديون شهرية ÷ دخل شهري","ضرائب","مدخرات"]'::jsonb,
   1,
   'Lenders use DTI to judge affordability. Lower is better.',
   'المقرضين بيستخدموا DTI لمعرفة القدرة على السداد… الأقل أحسن.',
   10),

  -- Gold / Silver (10 Q)
  ('q-gld-01', 'quiz-gold', '24K gold is what % pure?',
   'ذهب 24 قيراط نقاوته كام؟',
   '["24%","75%","99.9%","50%"]'::jsonb,
   '["24%","75%","99.9%","50%"]'::jsonb,
   2,
   '24-karat gold is ~99.9% pure (the rest is trace).',
   'ذهب 24 قيراط تقريبًا 99.9% نقاء.',
   1),
  ('q-gld-02', 'quiz-gold', '21K gold is what % pure?',
   'ذهب 21 قيراط نقاوته كام؟',
   '["75%","87.5%","99%","50%"]'::jsonb,
   '["75%","87.5%","99%","50%"]'::jsonb,
   1,
   '21K = 21/24 = 87.5% pure gold.',
   '21 قيراط = 21/24 = 87.5% ذهب.',
   2),
  ('q-gld-03', 'quiz-gold', 'Gold prices often rise when...',
   'سعر الذهب غالبًا يزيد لما...',
   '["Economy booms","Inflation or uncertainty rises","Interest rates rise","Stock market peaks"]'::jsonb,
   '["الاقتصاد بيطلع جامد","التضخم أو عدم اليقين يزيد","الفايدة تزيد","السوق يوصل للقمم"]'::jsonb,
   1,
   'Gold is a safe haven during inflation and economic uncertainty.',
   'الذهب ملاذ آمن وقت التضخم وعدم اليقين الاقتصادي.',
   3),
  ('q-gld-04', 'quiz-gold', 'Silver is generally...',
   'الفضة غالبًا...',
   '["More expensive than gold","Cheaper and more volatile","Only industrial","Obsolete"]'::jsonb,
   '["أغلى من الذهب","أرخص وأكثر تقلبًا","صناعي بس","قديم وميت"]'::jsonb,
   1,
   'Silver is ~1/70 the price of gold and has industrial + monetary uses.',
   'الفضة أرخص من الذهب بكتير وأكثر تقلبًا.',
   4),
  ('q-gld-05', 'quiz-gold', 'Physical gold storage should be...',
   'تخزين الذهب الفعلي المفروض يكون...',
   '["Under the bed","In a safe or bank deposit","In the car","At work"]'::jsonb,
   '["تحت السرير","في خزنة أو خزينة بنك","في العربية","في الشغل"]'::jsonb,
   1,
   'Safes or safety deposit boxes protect against theft and loss.',
   'خزنة أو خزينة بنك تحمي من السرقة والضياع.',
   5),
  ('q-gld-06', 'quiz-gold', 'Spot price of gold is...',
   'سعر السبوت للذهب يعني...',
   '["Retail price","Current market price per unit","Future price","Auction price"]'::jsonb,
   '["سعر التجزئة","سعر السوق الحالي للوحدة","سعر مستقبلي","سعر مزاد"]'::jsonb,
   1,
   'Spot price = current market price for immediate delivery.',
   'سعر السبوت = سعر السوق الحالي للتسليم الفوري.',
   6),
  ('q-gld-07', 'quiz-gold', 'Gold jewelry usually has...',
   'مجوهرات الذهب غالبًا فيها...',
   '["Same price as bullion","A premium for craftsmanship","Lower than bullion","No markup"]'::jsonb,
   '["نفس سعر السبائك","علاوة على المصنعية","أقل من السبائك","مافيش هامش"]'::jsonb,
   1,
   'Jewelry costs more than bullion due to craftsmanship and design.',
   'المشغولات أغلى من السبائك بسبب المصنعية والتصميم.',
   7),
  ('q-gld-08', 'quiz-gold', 'An ounce of gold equals about...',
   'أونصة الذهب تقريبًا بتساوي...',
   '["10 grams","28.35 grams","31.1 grams","100 grams"]'::jsonb,
   '["10 جرام","28.35 جرام","31.1 جرام","100 جرام"]'::jsonb,
   2,
   '1 troy ounce = 31.1 grams.',
   'أونصة تروي = 31.1 جرام.',
   8),
  ('q-gld-09', 'quiz-gold', 'Gold ETFs are...',
   'صناديق ETF للذهب يعني...',
   '["Physical gold only","Paper claims on gold","Silver","Bonds"]'::jsonb,
   '["دهب فعلي فقط","مطالبات ورقية على الذهب","فضة","سندات"]'::jsonb,
   1,
   'Gold ETFs hold gold in vaults on your behalf; you own shares.',
   'ETF بيمسك ذهب في خزائن نيابة عنك؛ أنت تمتلك وحدات.',
   9),
  ('q-gld-10', 'quiz-gold', 'Best reason to hold gold is...',
   'أحسن سبب تمسك بيه دهب...',
   '["Quick profit","Diversification & hedge","Dividends","Voting rights"]'::jsonb,
   '["ربح سريع","تنويع وتحوط","توزيعات","حقوق تصويت"]'::jsonb,
   1,
   'Gold diversifies a portfolio and hedges against currency weakness.',
   'الذهب بيوّع المحفظة وبيتحوط ضد ضعف العملة.',
   10)
on conflict (id) do update set
  quiz_id = excluded.quiz_id,
  question = excluded.question,
  question_ar = excluded.question_ar,
  options = excluded.options,
  options_ar = excluded.options_ar,
  correct_index = excluded.correct_index,
  explanation = excluded.explanation,
  explanation_ar = excluded.explanation_ar,
  sort_order = excluded.sort_order;

-- -----------------------------------------------------------------------------
-- FinTok (demo curated videos)
-- NOTE: `storage_path` is required even if `video_url` is used for demo.
-- Admin can later upload real videos to the `fintok` bucket and update rows.
-- -----------------------------------------------------------------------------
insert into public.fintok_videos (
  title,
  title_ar,
  creator_name,
  creator_name_ar,
  creator_avatar,
  caption,
  caption_ar,
  tags,
  simulation_route,
  storage_path,
  video_url,
  duration_seconds,
  sort_order,
  is_published,
  published_at
) values
  (
    '5 quick budgeting tips',
    '٥ نصائح سريعة للميزانية',
    'Fin-Game Team',
    'فريق Fin-Game',
    '👩‍🏫',
    'Save 10% first, then spend the rest.',
    'وفّر ١٠٪ الأول وبعدها اصرف الباقي.',
    '["budget","tips"]'::jsonb,
    '/simulation/banking',
    'demo/budgeting.mp4',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    15,
    1,
    true,
    now()
  ),
  (
    'Risk vs return in 30 seconds',
    'المخاطرة مقابل العائد في ٣٠ ثانية',
    'Fin-Game Team',
    'فريق Fin-Game',
    '👨‍🏫',
    'Higher return usually comes with higher risk.',
    'العائد الأعلى غالبًا معاه مخاطرة أعلى.',
    '["investing","basics"]'::jsonb,
    '/simulation/investment',
    'demo/risk-return.mp4',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    20,
    2,
    true,
    now()
  ),
  (
    'Credit score basics',
    'أساسيات الـ Credit Score',
    'Fin-Game Team',
    'فريق Fin-Game',
    '🧑‍💻',
    'Pay on time + keep utilization low.',
    'اسدد في الميعاد + خلّي نسبة الاستخدام قليلة.',
    '["credit","egypt"]'::jsonb,
    '/simulation/credit',
    'demo/credit-score.mp4',
    'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    30,
    3,
    true,
    now()
  )
on conflict do nothing;
