/** Major cities, districts, and towns in Egypt (EN + AR). */
export const EGYPT_CITIES = [
  'Cairo',
  'Giza',
  'Alexandria',
  'Shubra El Kheima',
  'Port Said',
  'Suez',
  'Luxor',
  'Mansoura',
  'El Mahalla El Kubra',
  'Tanta',
  'Asyut',
  'Ismailia',
  'Faiyum',
  'Zagazig',
  'Damietta',
  'Aswan',
  'Minya',
  'Damanhur',
  'Beni Suef',
  'Qena',
  'Sohag',
  'Hurghada',
  'Sharm El Sheikh',
  'Marsa Alam',
  'El Gouna',
  'Safaga',
  'Quseir',
  '6th of October City',
  'Sheikh Zayed City',
  'New Cairo',
  'Nasr City',
  'Maadi',
  'Heliopolis',
  'Mohandessin',
  'Dokki',
  'Agouza',
  'Imbaba',
  'Warraq',
  'Matariya',
  'Ain Shams',
  'Helwan',
  '15th of May City',
  'Badr City',
  'Shorouk City',
  'Obour City',
  'Madinaty',
  'Rehab City',
  'New Capital City',
  'Zamalek',
  'Garden City',
  'Downtown Cairo',
  'Sayeda Zeinab',
  'Old Cairo',
  'Mokattam',
  'Katameya',
  'Fifth Settlement',
  'First Settlement',
  'Third Settlement',
  'El Tagamoaa El Khames',
  'Hadayek El Ahram',
  'Haram',
  'Faisal',
  'Omraneya',
  'Boulaq',
  'Rod El Farag',
  'Zeitoun',
  'Hadayek El Kobba',
  'Sheraton',
  'Ard El Golf',
  'Smouha',
  'Stanley',
  'Miami',
  'Sidi Gaber',
  'Roushdy',
  'Gleem',
  'Louran',
  'Agami',
  'Borg El Arab',
  'Amreya',
  'Montaza',
  'Mandara',
  'Dekheila',
  'Abu Qir',
  'Talkha',
  'Belqas',
  'Mit Ghamr',
  'Sherbin',
  'Dikirnis',
  'Aga',
  'Senbellawein',
  'Manzala',
  'Kafr El Dawwar',
  'Edku',
  'Rashid',
  'Rosetta',
  'Desouk',
  'Bila',
  'Qutur',
  'Tala',
  'Ashmoun',
  'Sadat City',
  'Quesna',
  'Banha',
  'Khanka',
  'Shibin El Kom',
  'Toukh',
  'Qalyub',
  'Khosous',
  'Bilbeis',
  '10th of Ramadan City',
  'Abu Hammad',
  'Faqous',
  'Minya El Qamh',
  'Mashtool El Souk',
  'Mallawi',
  'Samalut',
  'Maghagha',
  'Beni Mazar',
  'Deir Mawas',
  'Abnoub',
  'Manfalut',
  'Dayrout',
  'Qus',
  'Naqada',
  'Edfu',
  'Kom Ombo',
  'Daraw',
  'Akhmim',
  'Tahta',
  'Girga',
  'Juhayna',
  'El Balyana',
  'Farshout',
  'Nag Hammadi',
  'Qift',
  'El Tor',
  'Saint Catherine',
  'Nuweiba',
  'Dahab',
  'Taba',
  'Rafah',
  'El Arish',
  'Bir El Abd',
  'Marsa Matruh',
  'El Hamam',
  'El Alamein',
  'Siwa',
  'Kharga',
  'Dakhla',
  'Farafra',
  'Balat',
  'Kharga City',
  'New Damietta',
  'Faraskur',
  'Kafr Saad',
  'Ras El Bar',
  'El Qanater El Khayreya',
  'القاهرة',
  'الجيزة',
  'الإسكندرية',
  'شبرا الخيمة',
  'بورسعيد',
  'السويس',
  'الأقصر',
  'المنصورة',
  'المحلة الكبرى',
  'طنطا',
  'أسيوط',
  'الإسماعيلية',
  'الفيوم',
  'الزقازيق',
  'دمياط',
  'أسوان',
  'المنيا',
  'دمنهور',
  'بني سويف',
  'قنا',
  'سوهاج',
  'الغردقة',
  'شرم الشيخ',
  'مرسى علم',
  'الجونة',
  'سفاجا',
  'القصير',
  'مدينة السادس من أكتوبر',
  'مدينة الشيخ زايد',
  'القاهرة الجديدة',
  'مدينة نصر',
  'المعادي',
  'مصر الجديدة',
  'المهندسين',
  'الدقي',
  'العجوزة',
  'إمبابة',
  'الوراق',
  'المطرية',
  'عين شمس',
  'حلوان',
  'مدينة 15 مايو',
  'مدينة بدر',
  'مدينة الشروق',
  'مدينة العبور',
  'مدينتي',
  'الرحاب',
  'العاصمة الإدارية',
  'الزمالك',
  'جاردن سيتي',
  'وسط البلد',
  'السيدة زينب',
  'مصر القديمة',
  'المقطم',
  'القطامية',
  'التجمع الخامس',
  'التجمع الأول',
  'التجمع الثالث',
  'حدائق الأهرام',
  'الهرم',
  'فيصل',
  'العمرانية',
  'بولاق',
  'روض الفرج',
  'الزيتون',
  'حدائق القبة',
  'شيراتون',
  'أرض الجولف',
  'سموحة',
  'ستانلي',
  'ميامي',
  'سيدي جابر',
  'رشدي',
  'جليم',
  'لوران',
  'العجمي',
  'برج العرب',
  'العامرية',
  'المنتزه',
  'المندرة',
  'الدخيلة',
  'أبو قير',
  'طلخا',
  'بلقاس',
  'ميت غمر',
  'شربين',
  'دكرنس',
  'أجا',
  'السنبلاوين',
  'المنزلة',
  'كفر الدوار',
  'إدكو',
  'رشيد',
  'دسوق',
  'بيلا',
  'قطور',
  'تلا',
  'أشمون',
  'مدينة السادات',
  'قويسنا',
  'بنها',
  'الخانكة',
  'شبين الكوم',
  'طوخ',
  'قليوب',
  'الخصوص',
  'بلبيس',
  'مدينة العاشر من رمضان',
  'أبو حماد',
  'فاقوس',
  'منيا القمح',
  'مشتول السوق',
  'ملوي',
  'سمالوط',
  'مغاغة',
  'بني مزار',
  'دير مواس',
  'أبنوب',
  'منفلوط',
  'ديروط',
  'قوص',
  'نجع حمادي',
  'قفط',
  'الطور',
  'سانت كاترين',
  'نويبع',
  'دهب',
  'طابا',
  'رفح',
  'العريش',
  'مرسى مطروح',
  'العلمين',
  'سيوة',
  'الخارجة',
  'الداخلة',
  'الفرافرة',
  'دمياط الجديدة',
  'فارسكور',
  'كفر سعد',
  'رأس البر',
  'القناطر الخيرية',
] as const;
