/** Common employers and sectors in Egypt (EN + AR). */
export const EGYPT_EMPLOYERS = [
  'National Bank of Egypt',
  'Banque Misr',
  'Commercial International Bank (CIB)',
  'QNB Alahli',
  'Arab African International Bank',
  'Banque du Caire',
  'Alex Bank',
  'Credit Agricole Egypt',
  'HSBC Egypt',
  'Citibank Egypt',
  'Emirates NBD Egypt',
  'Abu Dhabi Islamic Bank Egypt',
  'Faisal Islamic Bank',
  'Al Baraka Bank Egypt',
  'Suez Canal Bank',
  'Export Development Bank of Egypt',
  'Housing & Development Bank',
  'United Bank of Egypt',
  'Egyptian Gulf Bank',
  'MIDBANK',
  'Vodafone Egypt',
  'Orange Egypt',
  'Etisalat Misr',
  'Telecom Egypt',
  'WE Internet',
  'Amazon Egypt',
  'Microsoft Egypt',
  'Google Egypt',
  'IBM Egypt',
  'Oracle Egypt',
  'SAP Egypt',
  'Dell Technologies Egypt',
  'HP Egypt',
  'Cisco Egypt',
  'Intel Egypt',
  'Meta Egypt',
  'Apple Egypt',
  'Uber Egypt',
  'Careem Egypt',
  'Swvl',
  'Fawry',
  'Paymob',
  'Valu',
  'Telda',
  'Khazna',
  'MNT-Halan',
  'Rabbit',
  'Breadfast',
  'Talabat Egypt',
  'Elmenus',
  'Jumia Egypt',
  'Noon Egypt',
  'PwC Egypt',
  'Deloitte Egypt',
  'EY Egypt',
  'KPMG Egypt',
  'McKinsey Egypt',
  'BCG Egypt',
  'Bain Egypt',
  'Roland Berger Egypt',
  'Orascom Construction',
  'Elsewedy Electric',
  'Hassan Allam Holding',
  'Arab Contractors',
  'Petrojet',
  'Enppi',
  'EGPC',
  'EGAS',
  'Chevron Egypt',
  'Shell Egypt',
  'BP Egypt',
  'TotalEnergies Egypt',
  'Schlumberger Egypt',
  'Halliburton Egypt',
  'Juhayna',
  'Edita Food Industries',
  'Domty',
  'Panda Egypt',
  'Nestlé Egypt',
  'Unilever Egypt',
  'P&G Egypt',
  'Coca-Cola Egypt',
  'PepsiCo Egypt',
  'Heineken Egypt',
  'Almarai Egypt',
  'Lafarge Egypt',
  'Siemens Egypt',
  'Schneider Electric Egypt',
  'ABB Egypt',
  'General Electric Egypt',
  'Bosch Egypt',
  'Philip Morris Egypt',
  'BAT Egypt',
  'EgyptAir',
  'Alexandria Container & Cargo Handling',
  'DP World Sokhna',
  'Maersk Egypt',
  'FedEx Egypt',
  'DHL Egypt',
  'Aramex Egypt',
  'Ministry of Finance',
  'Ministry of Education',
  'Ministry of Health',
  'Ministry of Interior',
  'Ministry of Defense',
  'Central Bank of Egypt',
  'Egyptian Tax Authority',
  'Social Insurance Organization',
  'National Telecom Regulatory Authority',
  'Egyptian Exchange',
  'EFG Hermes',
  'CI Capital',
  'Beltone Financial',
  'Pharos Holding',
  'Mubasher Financial Services',
  'Cleopatra Hospitals Group',
  'Saudi German Hospital Egypt',
  'As-Salam International Hospital',
  'Dar Al Fouad Hospital',
  'Ain Shams University Hospitals',
  '57357 Hospital',
  'Bibliotheca Alexandrina',
  'Smart Village',
  'New Administrative Capital Companies',
  'SODIC',
  'Palm Hills Developments',
  'Talaat Moustafa Group',
  'Emaar Misr',
  'Mountain View',
  'Hyde Park Developments',
  'Orascom Development',
  'Misr Italia Properties',
  'Inertia Egypt',
  'Beta Egypt',
  'Freelance / Self-employed',
  'Startup',
  'Family Business',
  'Government / Public Sector',
  'NGO / Non-profit',
  'البنك الأهلي المصري',
  'بنك مصر',
  'البنك التجاري الدولي',
  'بنك قطر الوطني الأهلي',
  'بنك عرب أفريقي الدولي',
  'بنك القاهرة',
  'بنك الإسكندرية',
  'كريدي أجريكول مصر',
  'إتش إس بي سي مصر',
  'سيتي بنك مصر',
  'بنك أبوظبي الإسلامي مصر',
  'بنك فيصل الإسلامي',
  'بنك البركة مصر',
  'بنك قناة السويس',
  'بنك تنمية الصادرات',
  'بنك التعمير والإسكان',
  'المصرف المتحد',
  'بنك الخليج المصري',
  'فودافون مصر',
  'أورانج مصر',
  'اتصالات مصر',
  'المصرية للاتصالات',
  'وي إنترنت',
  'أمازون مصر',
  'مايكروسوفت مصر',
  'جوجل مصر',
  'آي بي إم مصر',
  'أوراكل مصر',
  'ساب مصر',
  'ديل تكنولوجيز مصر',
  'إتش بي مصر',
  'سيسكو مصر',
  'إنتل مصر',
  'ميتا مصر',
  'أبل مصر',
  'أوبر مصر',
  'كريم مصر',
  'سويفل',
  'فوري',
  'بيموب',
  'فاليو',
  'تلدا',
  'خزنة',
  'هالان',
  'رابت',
  'بريدفاست',
  'طلبات مصر',
  'إلمينيو',
  'جوميا مصر',
  'نون مصر',
  'بي دبليو سي مصر',
  'ديلويت مصر',
  'إرنست ويونغ مصر',
  'كي بي إم جي مصر',
  'ماكنزي مصر',
  'بي سي جي مصر',
  'بين مصر',
  'أوراسكوم للإنشاءات',
  'السويدي إلكتريك',
  'حسن علام',
  'المقاولون العرب',
  'بتروجت',
  'إنبي',
  'هيئة البترول',
  'إيجاس',
  'شيفرون مصر',
  'شل مصر',
  'بي بي مصر',
  'توتال إنرجيز مصر',
  'جهينة',
  'إيديتا للصناعات الغذائية',
  'دومتي',
  'بنده مصر',
  'نستله مصر',
  'يونيليفر مصر',
  'بروكتر آند جامبل مصر',
  'كوكاكولا مصر',
  'بيبسيكو مصر',
  'هاينكن مصر',
  'المراعي مصر',
  'سيمنز مصر',
  'جنرال إلكتريك مصر',
  'مصر للطيران',
  'وزارة المالية',
  'وزارة التربية والتعليم',
  'وزارة الصحة',
  'وزارة الداخلية',
  'البنك المركزي المصري',
  'مصلحة الضرائب المصرية',
  'الهيئة القومية للتأمينات',
  'البورصة المصرية',
  'إي إف جي هيرميس',
  'سي آي كابيتال',
  'بلتون المالية',
  'فاروس القابضة',
  'مباشر للخدمات المالية',
  'مجموعة مستشفيات كليوباترا',
  'المستشفى السعودي الألماني',
  'مستشفى السلام الدولي',
  'دار الفؤاد',
  'مستشفيات جامعة عين شمس',
  'مستشفى 57357',
  'مكتبة الإسكندرية',
  'القرية الذكية',
  'سوديك',
  'بالم هيلز',
  'طلعت مصطفى',
  'إعمار مصر',
  'ماونتن فيو',
  'هايد بارك',
  'أوراسكوم للتنمية',
  'مصر إيطاليا',
  'إنرشيا مصر',
  'عمل حر',
  'شركة ناشئة',
  'عمل عائلي',
  'حكومة / قطاع عام',
  'منظمة غير ربحية',
] as const;
