/** Faculties, majors, and fields of study (EN + AR). */
export const EGYPT_FACULTIES = [
  'Engineering',
  'Civil Engineering',
  'Mechanical Engineering',
  'Electrical Engineering',
  'Electronics & Communications',
  'Computer Engineering',
  'Architecture',
  'Urban Planning',
  'Medicine',
  'Dentistry',
  'Pharmacy',
  'Veterinary Medicine',
  'Nursing',
  'Physical Therapy',
  'Commerce',
  'Business Administration',
  'Accounting',
  'Finance',
  'Economics',
  'Marketing',
  'Law',
  'Political Science',
  'Arts',
  'English Language',
  'French Language',
  'German Language',
  'Arabic Language',
  'History',
  'Geography',
  'Philosophy',
  'Psychology',
  'Sociology',
  'Science',
  'Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'Geology',
  'Computer Science',
  'Information Systems',
  'Information Technology',
  'Software Engineering',
  'Data Science',
  'Artificial Intelligence',
  'Cybersecurity',
  'Mass Communication',
  'Media Studies',
  'Journalism',
  'Public Relations',
  'Advertising',
  'Fine Arts',
  'Applied Arts',
  'Music',
  'Theatre',
  'Cinema',
  'Agriculture',
  'Agricultural Engineering',
  'Food Science',
  'Education',
  'Special Education',
  'Kindergarten Education',
  'Physical Education',
  'Tourism & Hotels',
  'Hotel Management',
  'Aviation',
  'Navigation',
  'Maritime Transport',
  'Logistics & Supply Chain',
  'Industrial Education',
  'Technical Education',
  'Islamic Studies',
  'Sharia & Law',
  'Dar Al-Ulum',
  'Languages & Translation',
  'Biotechnology',
  'Environmental Science',
  'Renewable Energy',
  'Petroleum Engineering',
  'Mining Engineering',
  'Metallurgy',
  'Textile Engineering',
  'Chemical Engineering',
  'Biomedical Engineering',
  'Mechatronics',
  'Interior Design',
  'Graphic Design',
  'Fashion Design',
  'Public Health',
  'Nutrition',
  'Optometry',
  'Radiology',
  'Medical Laboratory',
  'Anesthesia',
  'هندسة',
  'هندسة مدنية',
  'هندسة ميكانيكية',
  'هندسة كهربائية',
  'هندسة إلكترونيات واتصالات',
  'هندسة حاسبات',
  'عمارة',
  'تخطيط عمراني',
  'طب',
  'طب أسنان',
  'صيدلة',
  'طب بيطري',
  'تمريض',
  'علاج طبيعي',
  'تجارة',
  'إدارة أعمال',
  'محاسبة',
  'مالية',
  'اقتصاد',
  'تسويق',
  'حقوق',
  'علوم سياسية',
  'آداب',
  'لغة إنجليزية',
  'لغة فرنسية',
  'لغة ألمانية',
  'لغة عربية',
  'تاريخ',
  'جغرافيا',
  'فلسفة',
  'علم نفس',
  'علم اجتماع',
  'علوم',
  'رياضيات',
  'فيزياء',
  'كيمياء',
  'أحياء',
  'جيولوجيا',
  'علوم حاسب',
  'نظم معلومات',
  'تكنولوجيا معلومات',
  'هندسة برمجيات',
  'علوم البيانات',
  'ذكاء اصطناعي',
  'أمن سيبراني',
  'إعلام',
  'إعلام واتصال',
  'صحافة',
  'علاقات عامة',
  'دعاية وإعلان',
  'فنون جميلة',
  'فنون تطبيقية',
  'موسيقى',
  'مسرح',
  'سينما',
  'زراعة',
  'هندسة زراعية',
  'علوم الأغذية',
  'تربية',
  'تربية خاصة',
  'تربية رياض أطفال',
  'تربية رياضية',
  'سياحة وفنادق',
  'إدارة فنادق',
  'طيران',
  'ملاحة',
  'نقل بحري',
  'لوجستيات وسلاسل إمداد',
  'تعليم صناعي',
  'تعليم فني',
  'دراسات إسلامية',
  'شريعة وقانون',
  'دار العلوم',
  'لغات وترجمة',
  'تكنولوجيا حيوية',
  'علوم بيئية',
  'طاقة متجددة',
  'هندسة بترول',
  'هندسة تعدين',
  'هندسة معادن',
  'هندسة نسيج',
  'هندسة كيميائية',
  'هندسة طبية حيوية',
  'ميكاترونكس',
  'تصميم داخلي',
  'تصميم جرافيك',
  'تصميم أزياء',
  'صحة عامة',
  'تغذية',
  'بصريات',
  'أشعة',
  'تحاليل طبية',
  'تخدير',
] as const;

export const ACADEMIC_YEARS = [
  'Kindergarten',
  'Primary 1',
  'Primary 2',
  'Primary 3',
  'Primary 4',
  'Primary 5',
  'Primary 6',
  'Preparatory 1',
  'Preparatory 2',
  'Preparatory 3',
  'Secondary 1',
  'Secondary 2',
  'Secondary 3',
  '1st Year University',
  '2nd Year University',
  '3rd Year University',
  '4th Year University',
  '5th Year University',
  '6th Year University',
  'Graduate',
  'Postgraduate Diploma',
  'Master\'s Degree',
  'PhD',
  'روضة',
  'الصف الأول الابتدائي',
  'الصف الثاني الابتدائي',
  'الصف الثالث الابتدائي',
  'الصف الرابع الابتدائي',
  'الصف الخامس الابتدائي',
  'الصف السادس الابتدائي',
  'الصف الأول الإعدادي',
  'الصف الثاني الإعدادي',
  'الصف الثالث الإعدادي',
  'الصف الأول الثانوي',
  'الصف الثاني الثانوي',
  'الصف الثالث الثانوي',
  'الأولى جامعة',
  'الثانية جامعة',
  'الثالثة جامعة',
  'الرابعة جامعة',
  'الخامسة جامعة',
  'السادسة جامعة',
  'خريج',
  'دبلوم دراسات عليا',
  'ماجستير',
  'دكتوراه',
] as const;
