/** Universities, colleges, and schools in Egypt (EN + AR). */
export const EGYPT_SCHOOLS = [
  'Cairo University',
  'Ain Shams University',
  'Alexandria University',
  'Assiut University',
  'Mansoura University',
  'Zagazig University',
  'Helwan University',
  'Minia University',
  'Suez Canal University',
  'Beni Suef University',
  'Tanta University',
  'Menoufia University',
  'South Valley University',
  'Fayoum University',
  'Damietta University',
  'Port Said University',
  'Suez University',
  'Luxor University',
  'Aswan University',
  'Arish University',
  'Sohag University',
  'Qena University',
  'Damanhour University',
  'Kafr El Sheikh University',
  'Benha University',
  'Al-Azhar University',
  'Sadat Academy for Management Sciences',
  'Arab Academy for Science and Technology',
  'Egypt-Japan University of Science and Technology',
  'American University in Cairo',
  'German University in Cairo',
  'British University in Egypt',
  'Canadian International College',
  'Future University in Egypt',
  'October 6 University',
  'Misr International University',
  'Modern Sciences and Arts University',
  'Pharos University in Alexandria',
  'Nile University',
  'New Giza University',
  'Galala University',
  'King Salman International University',
  'Egypt University of Informatics',
  'Al Alsun University',
  'Horus University',
  'Delta University for Science and Technology',
  'Sinai University',
  'El Sewedy University of Technology',
  'Badr University in Cairo',
  'Ahram Canadian University',
  'Arab Open University Egypt',
  'European Universities in Egypt',
  'Université Française d\'Égypte',
  'German International University',
  'Heliopolis University',
  'Nahda University',
  'Egyptian Russian University',
  'Egyptian Chinese University',
  'Merit University',
  'ESLSCA Business School',
  'AUC School of Continuing Education',
  'Faculty of Engineering Cairo University',
  'Faculty of Medicine Cairo University',
  'Faculty of Commerce Cairo University',
  'Military Technical College',
  'Police Academy Egypt',
  'Air Force Academy Egypt',
  'Naval Academy Egypt',
  'Cairo High Institute for Engineering',
  'Higher Technological Institute',
  'Institute of Aviation Engineering',
  'Maadi Military Academy',
  'Victory College',
  'Cairo American College',
  'Malvern College Egypt',
  'British International School Cairo',
  'New Cairo British International School',
  'Lycée Français du Caire',
  'Deutsche Schule der Borromäerinnen Kairo',
  'Schutz American School',
  'Modern English School Cairo',
  'International School of Choueifat',
  'Green Land International School',
  'Hayah International Academy',
  'Summits International School',
  'El Alsson School',
  'Narmer American College',
  'Capital International School',
  'Roots International School',
  'Manarat El Mostaqbal',
  'Al Orman School',
  'Thanaweya Amma Public School',
  'Thanaweya Amma Experimental School',
  'Azhari Secondary School',
  'Technical Secondary School',
  'Industrial Secondary School',
  'Commercial Secondary School',
  'جامعة القاهرة',
  'جامعة عين شمس',
  'جامعة الإسكندرية',
  'جامعة أسيوط',
  'جامعة المنصورة',
  'جامعة الزقازيق',
  'جامعة حلوان',
  'جامعة المنيا',
  'جامعة قناة السويس',
  'جامعة بني سويف',
  'جامعة طنطا',
  'جامعة المنوفية',
  'جامعة جنوب الوادي',
  'جامعة الفيوم',
  'جامعة دمياط',
  'جامعة بورسعيد',
  'جامعة السويس',
  'جامعة الأقصر',
  'جامعة أسوان',
  'جامعة العريش',
  'جامعة سوهاج',
  'جامعة قنا',
  'جامعة دمنهور',
  'جامعة كفر الشيخ',
  'جامعة بنها',
  'الأزهر الشريف',
  'أكاديمية السادات للعلوم الإدارية',
  'الأكاديمية العربية للعلوم والتكنولوجيا',
  'الجامعة المصرية اليابانية للعلوم والتكنولوجيا',
  'الجامعة الأمريكية بالقاهرة',
  'الجامعة الألمانية بالقاهرة',
  'الجامعة البريطانية في مصر',
  'الكلية الكندية الدولية',
  'جامعة المستقبل في مصر',
  'جامعة 6 أكتوبر',
  'جامعة مصر الدولية',
  'جامعة أكتوبر للعلوم الحديثة والآداب',
  'جامعة فاروس بالإسكندرية',
  'جامعة النيل',
  'جامعة الجلالة',
  'جامعة الملك سلمان الدولية',
  'جامعة مصر للمعلوماتية',
  'جامعة الألسن',
  'جامعة حورس',
  'جامعة الدلتا للعلوم والتكنولوجيا',
  'جامعة سيناء',
  'جامعة السويدي للتكنولوجيا',
  'جامعة بدر بالقاهرة',
  'جامعة الأهرام الكندية',
  'الجامعة العربية المفتوحة مصر',
  'الجامعات الأوروبية في مصر',
  'الجامعة الفرنسية في مصر',
  'الجامعة الألمانية الدولية',
  'جامعة هليوبوليس',
  'جامعة النهضة',
  'الجامعة المصرية الروسية',
  'الجامعة المصرية الصينية',
  'جامعة ميريت',
  'كلية الهندسة جامعة القاهرة',
  'كلية الطب جامعة القاهرة',
  'كلية التجارة جامعة القاهرة',
  'الكلية الفنية العسكرية',
  'كلية الشرطة',
  'كلية الطيران الجوي',
  'كلية البحرية',
  'المعهد العالي للهندسة بالقاهرة',
  'المعهد التكنولوجي العالي',
  'معهد هندسة الطيران',
  'كلية المعراج العسكرية',
  'المدرسة الأمريكية بالقاهرة',
  'كلية مالفيرن مصر',
  'المدرسة البريطانية الدولية بالقاهرة',
  'المدرسة البريطانية بالقاهرة الجديدة',
  'المدرسة الفرنسية بالقاهرة',
  'المدرسة الألمانية بالقاهرة',
  'مدرسة شوتز الأمريكية',
  'المدرسة الإنجليزية الحديثة',
  'مدارس الشويفات الدولية',
  'مدرسة جرين لاند الدولية',
  'أكاديمية حياة الدولية',
  'مدرسة سمتس الدولية',
  'مدرسة الليسيه',
  'كلية نارمر الأمريكية',
  'مدرسة كابيتال الدولية',
  'مدرسة روتس الدولية',
  'مدارس منارات المستقبل',
  'مدرسة الأورمان',
  'ثانوية عامة',
  'ثانوية عامة تجريبي',
  'ثانوية أزهرية',
  'ثانوية فنية',
  'ثانوية صناعية',
  'ثانوية تجارية',
  'إعدادية',
  'ابتدائية',
  'روضة أطفال',
  'مدرسة دولية',
  'معهد خاص',
  'Zagazig National University',
  'Matrouh University',
  'New Valley University',
  'Nile Academy',
  'Ain Shams High Institute',
  'Higher Institute of Engineering & Technology',
  'Academy of Arts',
  'Academy of Scientific Research',
  'Institute of National Planning',
  'Institute of Environmental Studies',
  'Cairo Higher Institute for Computers',
  'Misr Higher Institute for Engineering',
  'October Higher Institute for Engineering',
  'Higher Institute for Management & Accounting',
  'Higher Institute for Tourism & Hotels',
  'Higher Institute for Languages',
  'Higher Institute for Cooperative Management',
  'Higher Institute for Social Service',
  'Higher Institute for Specific Education',
  'Egyptian Aviation Academy',
  'Egyptian Aviation Academy EAA',
  'Egyptian Military Academy',
  'Armed Forces Technical Institute',
  'Nasser Higher Military Academy',
  'Naval Technical Institute',
  'Air Defense College',
  'Border Guards College',
  'Central Agency for Public Mobilization Institute',
  'Banking Institute of Egypt',
  'Institute of Finance & Business',
  'Institute of Chartered Accountants',
  'Regional Center for Training',
  'National Institute for Governance',
  'National Training Institute',
  'Information Technology Institute ITI',
  'Information Technology Institute Ismailia',
  'Information Technology Institute Mansoura',
  'Information Technology Institute Alexandria',
  'Information Technology Institute Assiut',
  'Information Technology Institute Aswan',
  'Information Technology Institute Smart Village',
  'Egyptian E-Learning University',
  'Egyptian Russian University',
  'Egyptian Chinese University',
  'Egyptian Japanese University',
  'Canadian International College CIC',
  'Modern Academy Maadi',
  'Modern Academy for Computer Science',
  'Modern Academy for Engineering',
  'Higher Technological Institute 10th Ramadan',
  'Higher Technological Institute 6th October',
  'Higher Technological Institute Menoufia',
  'Higher Technological Institute Kafr El Sheikh',
  'Higher Technological Institute Beni Suef',
  'Higher Technological Institute Minya',
  'Higher Technological Institute Aswan',
  'Higher Technological Institute Ismailia',
  'Higher Technological Institute Port Said',
  'Higher Technological Institute Suez',
  'Higher Technological Institute Damietta',
  'Higher Technological Institute Fayoum',
  'Higher Technological Institute Sohag',
  'Higher Technological Institute Qena',
  'Higher Technological Institute Luxor',
  'Higher Technological Institute Matrouh',
  'Higher Technological Institute North Sinai',
  'Higher Technological Institute South Sinai',
  'Higher Technological Institute New Valley',
  'Faculty of Engineering Ain Shams University',
  'Faculty of Engineering Alexandria University',
  'Faculty of Engineering Mansoura University',
  'Faculty of Engineering Zagazig University',
  'Faculty of Engineering Tanta University',
  'Faculty of Engineering Minia University',
  'Faculty of Engineering Assiut University',
  'Faculty of Engineering Suez Canal University',
  'Faculty of Medicine Ain Shams University',
  'Faculty of Medicine Alexandria University',
  'Faculty of Pharmacy Cairo University',
  'Faculty of Dentistry Cairo University',
  'Faculty of Alsun Ain Shams University',
  'Faculty of Commerce Ain Shams University',
  'Faculty of Law Cairo University',
  'Faculty of Arts Cairo University',
  'Faculty of Science Cairo University',
  'Faculty of Agriculture Cairo University',
  'Faculty of Veterinary Medicine Cairo University',
  'Faculty of Nursing Cairo University',
  'Faculty of Physical Therapy Cairo University',
  'Faculty of Applied Arts Helwan University',
  'Faculty of Fine Arts Helwan University',
  'Faculty of Tourism & Hotels Helwan University',
  'Faculty of Computers & Information Cairo University',
  'Faculty of Economics & Political Science Cairo University',
  'Faculty of Mass Communication Cairo University',
  'Faculty of Archaeology Cairo University',
  'Faculty of Dar Al-Ulum Cairo University',
  'Faculty of Kindergarten Cairo University',
  'Faculty of Specific Education Cairo University',
  'Faculty of Education Cairo University',
  'Faculty of Oral & Dental Medicine Cairo University',
  'STEM School Egypt',
  'STEM High School 6th October',
  'STEM High School Alexandria',
  'STEM High School Dakahlia',
  'STEM High School Giza',
  'STEM High School Ismailia',
  'STEM High School Luxor',
  'STEM High School Mansoura',
  'STEM High School Minya',
  'STEM High School Port Said',
  'STEM High School Red Sea',
  'STEM High School Sharqia',
  'STEM High School Sohag',
  'STEM High School Suez',
  'STEM High School Aswan',
  'STEM High School Beni Suef',
  'STEM High School Fayoum',
  'STEM High School Qena',
  'Maadi British International School',
  'Cairo English School',
  'New Generation International Schools',
  'Egyptian International School',
  'Royal International School',
  'Kent College West Cairo',
  'Repton School Cairo',
  'Cairo West International School',
  'El Nasr Boys School',
  'El Nasr Girls College',
  'Victory College Cairo',
  'Collège de la Sainte Famille',
  'Collège Saint Marc',
  'Collège Notre Dame des Apôtres',
  'Saint Joseph School',
  'Saint Fatima School',
  'Saint George School',
  'Saint Mary School',
  'Deutsche Evangelische Oberschule',
  'Italian School Cairo',
  'Pakistan International School Cairo',
  'Indian School Cairo',
  'Japanese School Cairo',
  'Russian School Cairo',
  'Chinese School Cairo',
  'Korean School Cairo',
  'Canadian International School Egypt',
  'American International School Egypt',
  'British School Al Rehab',
  'British School Madinaty',
  'British School New Cairo',
  'International School of Elite',
  'Future International School',
  'Genius International School',
  'Leaders International School',
  'Mentor International School',
  'Pioneers International School',
  'Summit International School',
  'Wellington School Cairo',
  'Westminster School Cairo',
  'Oxford International School',
  'Cambridge International School Egypt',
  'Pearson International School',
  'Beacon International School',
  'Dolphin International School',
  'Eagles International School',
  'Futures Language Schools',
  'Language Schools Egypt',
  'National Language Schools',
  'Modern Language School',
  'International Language School',
  'El Alsson British Division',
  'El Alsson American Division',
  'جامعة مطروح',
  'جامعة الوادي الجديد',
  'أكاديمية الفنون',
  'أكاديمية البحث العلمي',
  'معهد التخطيط القومي',
  'معهد الدراسات البيئية',
  'المعهد العالي للحاسبات بالقاهرة',
  'معهد مصر العالي للهندسة',
  'المعهد العالي للهندسة بأكتوبر',
  'المعهد العالي للإدارة والمحاسبة',
  'المعهد العالي للسياحة والفنادق',
  'المعهد العالي للغات',
  'المعهد العالي للتعاون الزراعي',
  'المعهد العالي للخدمة الاجتماعية',
  'المعهد العالي للتربية النوعية',
  'أكاديمية الطيران المصرية',
  'الكلية الحربية',
  'المعهد الفني للقوات المسلحة',
  'كلية الدفاع الجوي',
  'كلية حرس الحدود',
  'معهد البنك المركزي المصري',
  'معهد المحاسبين والمراجعين',
  'معهد تكنولوجيا المعلومات',
  'معهد تكنولوجيا المعلومات بالإسماعيلية',
  'معهد تكنولوجيا المعلومات بالمنصورة',
  'معهد تكنولوجيا المعلومات بالإسكندرية',
  'معهد تكنولوجيا المعلومات بأسيوط',
  'معهد تكنولوجيا المعلومات بأسوان',
  'معهد تكنولوجيا المعلومات بالقرية الذكية',
  'الأكاديمية الحديثة بالمعادي',
  'الأكاديمية الحديثة لعلوم الحاسب',
  'الأكاديمية الحديثة للهندسة',
  'المعهد التكنولوجي العالي بمدينة العاشر من رمضان',
  'المعهد التكنولوجي العالي بالسادس من أكتوبر',
  'المعهد التكنولوجي العالي بالمنوفية',
  'المعهد التكنولوجي العالي بكفر الشيخ',
  'المعهد التكنولوجي العالي ببني سويف',
  'المعهد التكنولوجي العالي بالمنيا',
  'المعهد التكنولوجي العالي بأسوان',
  'المعهد التكنولوجي العالي بالإسماعيلية',
  'المعهد التكنولوجي العالي ببورسعيد',
  'المعهد التكنولوجي العالي بالسويس',
  'المعهد التكنولوجي العالي بدمياط',
  'المعهد التكنولوجي العالي بالفيوم',
  'المعهد التكنولوجي العالي بسوهاج',
  'المعهد التكنولوجي العالي بقنا',
  'المعهد التكنولوجي العالي بالأقصر',
  'المعهد التكنولوجي العالي بمطروح',
  'كلية الهندسة جامعة عين شمس',
  'كلية الهندسة جامعة الإسكندرية',
  'كلية الهندسة جامعة المنصورة',
  'كلية الهندسة جامعة الزقازيق',
  'كلية الهندسة جامعة طنطا',
  'كلية الهندسة جامعة المنيا',
  'كلية الهندسة جامعة أسيوط',
  'كلية الهندسة جامعة قناة السويس',
  'كلية الطب جامعة عين شمس',
  'كلية الطب جامعة الإسكندرية',
  'كلية الصيدلة جامعة القاهرة',
  'كلية طب الأسنان جامعة القاهرة',
  'كلية الألسن جامعة عين شمس',
  'كلية التجارة جامعة عين شمس',
  'كلية الحقوق جامعة القاهرة',
  'كلية الآداب جامعة القاهرة',
  'كلية العلوم جامعة القاهرة',
  'كلية الزراعة جامعة القاهرة',
  'كلية الطب البيطري جامعة القاهرة',
  'كلية التمريض جامعة القاهرة',
  'كلية العلاج الطبيعي جامعة القاهرة',
  'كلية التطبيقية جامعة حلوان',
  'كلية الفنون الجميلة جامعة حلوان',
  'كلية السياحة والفنادق جامعة حلوان',
  'كلية الحاسبات والمعلومات جامعة القاهرة',
  'كلية الاقتصاد والعلوم السياسية جامعة القاهرة',
  'كلية الإعلام جامعة القاهرة',
  'كلية الآثار جامعة القاهرة',
  'كلية دار العلوم جامعة القاهرة',
  'كلية رياض الأطفال جامعة القاهرة',
  'كلية التربية النوعية جامعة القاهرة',
  'كلية التربية جامعة القاهرة',
  'مدرسة ستيم المصرية',
  'مدرسة النصر للبنين',
  'مدرسة النصر للبنات',
  'كلية السانت فاميل',
  'كلية سان مارك',
  'مدرسة القديس يوسف',
  'مدرسة القديسة فاطمة',
  'مدرسة القديس جورج',
  'مدرسة القديسة مريم',
  'المدرسة الإيطالية بالقاهرة',
  'المدرسة الباكستانية بالقاهرة',
  'المدرسة الهندية بالقاهرة',
  'المدرسة اليابانية بالقاهرة',
  'المدرسة الروسية بالقاهرة',
  'المدرسة الصينية بالقاهرة',
  'المدرسة الكورية بالقاهرة',
  'المدرسة الكندية الدولية',
  'المدرسة الأمريكية الدولية',
  'المدرسة البريطانية بالرحاب',
  'المدرسة البريطانية بمدينتي',
  'مدرسة المستقبل الدولية',
  'مدرسة القادة الدولية',
  'مدرسة الجينيوس الدولية',
  'مدرسة ويلينجتون بالقاهرة',
  'مدرسة ويستمنستر بالقاهرة',
  'مدرسة أكسفورد الدولية',
  'مدرسة كامبريدج الدولية',
  'مدارس اللغات المستقبل',
  'مدارس اللغات الوطنية',
  'المدرسة اللغوية الحديثة',
  'المدرسة اللغوية الدولية',
  'قسم اللغات الإنجليزية الألsson',
  'قسم اللغات الأمريكية الألsson',
] as const;
