import { Prisma } from '@prisma/client';

export const meUserSelect = {
  id: true,
  email: true,
  isAdmin: true,
  displayName: true,
  avatar: true,
  level: true,
  coins: true,
  xp: true,
  streak: true,
  longestStreak: true,
  lastActiveDate: true,
  dateOfBirth: true,
  gender: true,
  mobile: true,
  governorate: true,
  city: true,
  userType: true,
  schoolName: true,
  facultyMajor: true,
  academicYear: true,
  employer: true,
  monthlyIncomeRange: true,
  financialGoals: true,
  financialLiteracy: true,
  persona: true,
  parentEmail: true,
  parentPhone: true,
  referredByCode: true,
  referralCode: true,
  profileCompletedAt: true,
  createdAt: true,
  updatedAt: true,
} satisfies Prisma.UserSelect;
