-- AlterTable
ALTER TABLE `User` ADD COLUMN `dateOfBirth` DATETIME(3) NULL,
    ADD COLUMN `gender` VARCHAR(32) NULL,
    ADD COLUMN `mobile` VARCHAR(32) NULL,
    ADD COLUMN `governorate` VARCHAR(120) NULL,
    ADD COLUMN `city` VARCHAR(120) NULL,
    ADD COLUMN `userType` VARCHAR(32) NULL,
    ADD COLUMN `schoolName` VARCHAR(200) NULL,
    ADD COLUMN `facultyMajor` VARCHAR(200) NULL,
    ADD COLUMN `academicYear` VARCHAR(64) NULL,
    ADD COLUMN `employer` VARCHAR(200) NULL,
    ADD COLUMN `monthlyIncomeRange` VARCHAR(64) NULL,
    ADD COLUMN `financialGoals` TEXT NULL,
    ADD COLUMN `financialLiteracy` VARCHAR(32) NULL,
    ADD COLUMN `persona` VARCHAR(64) NULL,
    ADD COLUMN `parentEmail` VARCHAR(200) NULL,
    ADD COLUMN `parentPhone` VARCHAR(32) NULL,
    ADD COLUMN `referredByCode` VARCHAR(64) NULL,
    ADD COLUMN `profileCompletedAt` DATETIME(3) NULL;
